"""AUTO-GENERATED by analysis/gen_error_keys.py — do not edit by hand.

Maps the fixed ValueError messages raised by benchmarks/tau3-bench/harness/retail/tools.py to stable keys.
Regenerate after any harness change: uv run python -m analysis.gen_error_keys
"""

from __future__ import annotations

import re

ERROR_KEY_PATTERNS: tuple[tuple[str, str], ...] = (
    ('insufficient_gift_card_balance_to_pay_for_the_new_item', 'Insufficient\\ gift\\ card\\ balance\\ to\\ pay\\ for\\ the\\ new\\ item'),
    ('insufficient_gift_card_balance_to_pay_for_the_order', 'Insufficient\\ gift\\ card\\ balance\\ to\\ pay\\ for\\ the\\ order'),
    ('insufficient_gift_card_balance_to_pay_for_the_price_difference', 'Insufficient\\ gift\\ card\\ balance\\ to\\ pay\\ for\\ the\\ price\\ difference'),
    ('invalid_characters_in_expression', 'Invalid\\ characters\\ in\\ expression'),
    ('invalid_reason', 'Invalid\\ reason'),
    ('item_not_found', 'Item\\ not\\ found'),
    ('non_delivered_order_cannot_be_exchanged', 'Non\\-delivered\\ order\\ cannot\\ be\\ exchanged'),
    ('non_delivered_order_cannot_be_returned', 'Non\\-delivered\\ order\\ cannot\\ be\\ returned'),
    ('non_pending_order_cannot_be_cancelled', 'Non\\-pending\\ order\\ cannot\\ be\\ cancelled'),
    ('non_pending_order_cannot_be_modified', 'Non\\-pending\\ order\\ cannot\\ be\\ modified'),  # 3 raise sites
    ('order_not_found', 'Order\\ not\\ found'),
    ('payment_method_not_found', 'Payment\\ method\\ not\\ found'),
    ('payment_method_should_be_the_original_payment_method', 'Payment\\ method\\ should\\ be\\ the\\ original\\ payment\\ method'),
    ('product_not_found', 'Product\\ not\\ found'),
    ('some_item_not_found', 'Some\\ item\\ not\\ found'),
    ('the_new_item_id_should_be_different_from_the_old_item_id', 'The\\ new\\ item\\ id\\ should\\ be\\ different\\ from\\ the\\ old\\ item\\ id'),
    ('the_new_payment_method_should_be_different_from_the_current_one', 'The\\ new\\ payment\\ method\\ should\\ be\\ different\\ from\\ the\\ current\\ one'),
    ('the_number_of_items_to_be_exchanged_should_match', 'The\\ number\\ of\\ items\\ to\\ be\\ exchanged\\ should\\ match'),
    ('the_number_of_items_to_be_exchanged_should_match_2', 'The\\ number\\ of\\ items\\ to\\ be\\ exchanged\\ should\\ match\\.'),
    ('there_should_be_exactly_one_payment_for_a_pending_order', 'There\\ should\\ be\\ exactly\\ one\\ payment\\ for\\ a\\ pending\\ order'),
    ('user_not_found', 'User\\ not\\ found'),  # 3 raise sites
    ('variant_not_found', 'Variant\\ not\\ found'),
    ('x_not_found', '(.+?)\\ not\\ found'),
    ('item_x_not_found', 'Item\\ (.+?)\\ not\\ found'),  # 3 raise sites
    ('new_item_x_not_found_or_available', 'New\\ item\\ (.+?)\\ not\\ found\\ or\\ available'),  # 2 raise sites
    ('number_of_x_not_found', 'Number\\ of\\ (.+?)\\ not\\ found\\.'),
)

_COMPILED: tuple[tuple[str, re.Pattern[str], int], ...] = tuple(
    (key, re.compile(pattern), len(pattern.replace("(.+?)", "")))
    for key, pattern in ERROR_KEY_PATTERNS
)


def match_error_key(message: str) -> str:
    """Map a tool error message (with or without the "Error: " prefix) to its key.

    When several patterns match (a template like "(.+?) not found" overlaps the
    exact messages), the one with the most literal characters wins. Zero matches
    or a literal-length tie between distinct keys raises LookupError: the table
    is stale and must be regenerated from source, never patched around.
    """
    text = message.removeprefix("Error: ")
    matches = sorted(
        ((literal, key) for key, pattern, literal in _COMPILED if pattern.fullmatch(text)),
        reverse=True,
    )
    if not matches or (len(matches) > 1 and matches[0][0] == matches[1][0]):
        raise LookupError(
            f"no unambiguous error-key match for {text!r} (candidates: {matches!r}); "
            "regenerate with: uv run python -m analysis.gen_error_keys"
        )
    return matches[0][1]
