"""Regenerate analysis/error_keys.py from the harness retail toolkit source.

Every `raise ValueError(...)` in the retail tools becomes a (key, regex) row:
string literals map to exact patterns, f-string slots become capture groups.
Non-literal raise arguments abort generation — the table must stay complete.

Usage: uv run python -m analysis.gen_error_keys
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

DEFAULT_TOOLS_PATH = Path("benchmarks/tau3-bench/harness/retail/tools.py")
DEFAULT_OUTPUT_PATH = Path("analysis/error_keys.py")

_SLOT = "\x00"

_HEADER = '''"""AUTO-GENERATED by analysis/gen_error_keys.py — do not edit by hand.

Maps the fixed ValueError messages raised by {source} to stable keys.
Regenerate after any harness change: uv run python -m analysis.gen_error_keys
"""

from __future__ import annotations

import re

ERROR_KEY_PATTERNS: tuple[tuple[str, str], ...] = (
'''

_FOOTER = ''')

_COMPILED: tuple[tuple[str, re.Pattern[str], int], ...] = tuple(
    (key, re.compile(pattern), len(pattern.replace("(.+?)", "")))
    for key, pattern in ERROR_KEY_PATTERNS
)


def match_error_key(message: str) -> str:
    """Map a tool error message (with or without the "Error: " prefix) to its key.

    When several patterns match (a template like "(.+?) not found" overlaps the
    exact messages), the one with the most literal characters wins. Zero matches
    or a literal-length tie between distinct keys raises LookupError: the table
    is stale and must be regenerated from source, never patched around.
    """
    text = message.removeprefix("Error: ")
    matches = sorted(
        ((literal, key) for key, pattern, literal in _COMPILED if pattern.fullmatch(text)),
        reverse=True,
    )
    if not matches or (len(matches) > 1 and matches[0][0] == matches[1][0]):
        raise LookupError(
            f"no unambiguous error-key match for {text!r} (candidates: {matches!r}); "
            "regenerate with: uv run python -m analysis.gen_error_keys"
        )
    return matches[0][1]
'''


def extract_templates(tools_path: Path) -> dict[str, int]:
    """Return {template: raise-site count}, with f-string slots as _SLOT markers."""
    tree = ast.parse(tools_path.read_text(), filename=str(tools_path))
    templates: dict[str, int] = {}
    rejected: list[int] = []
    for node in ast.walk(tree):
        if not (
            isinstance(node, ast.Raise)
            and isinstance(node.exc, ast.Call)
            and isinstance(node.exc.func, ast.Name)
            and node.exc.func.id == "ValueError"
        ):
            continue
        if len(node.exc.args) != 1:
            rejected.append(node.lineno)
            continue
        template = _template_from(node.exc.args[0])
        if template is None:
            rejected.append(node.lineno)
        else:
            templates[template] = templates.get(template, 0) + 1
    if rejected:
        raise SystemExit(
            f"{tools_path}: non-literal ValueError messages at lines {rejected}; "
            "extend gen_error_keys.py deliberately instead of skipping them"
        )
    return templates


def _template_from(arg: ast.expr) -> str | None:
    if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
        return arg.value
    if isinstance(arg, ast.JoinedStr):
        parts: list[str] = []
        for value in arg.values:
            if isinstance(value, ast.Constant) and isinstance(value.value, str):
                parts.append(value.value)
            elif isinstance(value, ast.FormattedValue):
                parts.append(_SLOT)
            else:
                return None
        return "".join(parts)
    return None


def build_table(templates: dict[str, int]) -> list[tuple[str, str, int]]:
    """Return deterministic (key, regex, site_count) rows, exact patterns first."""
    rows: list[tuple[str, str, int]] = []
    used_keys: dict[str, int] = {}
    ordered = sorted(templates, key=lambda t: (_SLOT in t, t))
    for template in ordered:
        base = re.sub(
            r"_+", "_", re.sub(r"[^a-z0-9]+", "_", _slug_text(template))
        ).strip("_")
        used_keys[base] = used_keys.get(base, 0) + 1
        key = base if used_keys[base] == 1 else f"{base}_{used_keys[base]}"
        pattern = "".join(
            "(.+?)" if chunk == _SLOT else re.escape(chunk)
            for chunk in re.split(f"({_SLOT})", template)
            if chunk
        )
        rows.append((key, pattern, templates[template]))
    return rows


def _slug_text(template: str) -> str:
    return template.replace(_SLOT, " x ").lower()


def write_module(
    rows: list[tuple[str, str, int]], tools_path: Path, output_path: Path
) -> None:
    lines = [_HEADER.format(source=tools_path)]
    for key, pattern, count in rows:
        suffix = f"  # {count} raise sites" if count > 1 else ""
        lines.append(f"    ({key!r}, {pattern!r}),{suffix}\n")
    lines.append(_FOOTER)
    output_path.write_text("".join(lines))


def main(
    tools_path: Path = DEFAULT_TOOLS_PATH, output_path: Path = DEFAULT_OUTPUT_PATH
) -> None:
    templates = extract_templates(tools_path)
    rows = build_table(templates)
    write_module(rows, tools_path, output_path)
    n_sites = sum(count for _, _, count in rows)
    print(f"wrote {output_path}: {len(rows)} keys from {n_sites} raise sites")


if __name__ == "__main__":
    main(*(Path(a) for a in sys.argv[1:]))
